<?php

namespace SmartContentAI\Frontend;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Schema {

	public function insert_schema_json_ld() {
		if ( ! is_single() ) {
			return;
		}

		global $post;
		// Check if this post was generated by our plugin (via meta flag) or just apply generally
		// For now, applying to all posts for better utility

		$excerpt = get_post_meta( $post->ID, '_smartcontentai_meta_desc', true );
		if ( ! $excerpt ) {
			$excerpt = wp_trim_words( $post->post_content, 20 );
		}

		$schema = array(
			'@context'      => 'https://schema.org',
			'@type'         => 'Article',
			'headline'      => get_the_title(),
			'description'   => $excerpt,
			'datePublished' => get_the_date( 'c' ),
			'dateModified'  => get_the_modified_date( 'c' ),
			'author'        => array(
				'@type' => 'Person',
				'name'  => get_the_author(),
			),
		);

		if ( has_post_thumbnail() ) {
			$schema['image'] = get_the_post_thumbnail_url( null, 'full' );
		}

		echo '<script type="application/ld+json">' . json_encode( $schema ) . '</script>';
	}
}
